### ISSUE TITLE
在 centos7下安装报错

### ISSUE THREAD

**Issue by chinakids** [DoubleSpout/ccap#48]
```
gcc:4.8+
python:2.7
```

```
npm http GET https://registry.npmjs.org/ccap
npm http 304 https://registry.npmjs.org/ccap
npm WARN engine ccap@0.6.4: wanted: {"node":">=0.12.0"} (current: {"node":"v0.10.36","npm":"1.3.6"})

> ccap@0.6.4 preinstall /home/Lawrence/node_modules/ccap
> node make.js

I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api and lightweight.

starting compile ccap! good luck!
npm http GET https://registry.npmjs.org/node-schedule/0.1.13
npm http GET https://registry.npmjs.org/nan/1.7.0
npm http GET https://registry.npmjs.org/async/1.4.2
npm http 304 https://registry.npmjs.org/async/1.4.2
npm http 304 https://registry.npmjs.org/nan/1.7.0
npm http 304 https://registry.npmjs.org/node-schedule/0.1.13

> ccap@0.6.4 install /home/Lawrence/node_modules/ccap
> node-gyp rebuild

make: 进入目录“/home/Lawrence/node_modules/ccap/build”
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jaricom.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcapimin.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcapistd.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcarith.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jccoefct.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jccolor.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcdctmgr.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jchuff.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcinit.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcmainct.o
../addon/jpeglib/jcmainct.c: 在函数‘start_pass_main’中:
../addon/jpeglib/jcmainct.c:71:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jcmainct.c: 在函数‘process_data_simple_main’中:
../addon/jpeglib/jcmainct.c:117:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jcmainct.c: 在函数‘jinit_c_main_controller’中:
../addon/jpeglib/jcmainct.c:247:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main;
               ^
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcmarker.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcmaster.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcomapi.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcparam.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcprepct.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jcsample.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jctrans.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdapimin.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdapistd.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdarith.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdatadst.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdatasrc.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdcoefct.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdcolor.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jddctmgr.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdhuff.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdinput.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmainct.o
../addon/jpeglib/jdmainct.c: 在函数‘alloc_funny_pointers’中:
../addon/jpeglib/jdmainct.c:162:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘make_funny_pointers’中:
../addon/jpeglib/jdmainct.c:203:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘set_wraparound_pointers’中:
../addon/jpeglib/jdmainct.c:243:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘set_bottom_pointers’中:
../addon/jpeglib/jdmainct.c:272:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘start_pass_main’中:
../addon/jpeglib/jdmainct.c:309:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘process_data_simple_main’中:
../addon/jpeglib/jdmainct.c:349:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘process_data_context_main’中:
../addon/jpeglib/jdmainct.c:389:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main = (my_main_ptr) cinfo->main;
               ^
../addon/jpeglib/jdmainct.c: 在函数‘jinit_d_main_controller’中:
../addon/jpeglib/jdmainct.c:478:15: 警告：‘main’通常是一个函数 [-Wmain]
   my_main_ptr main;
               ^
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmarker.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmaster.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdmerge.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdpostct.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdsample.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jdtrans.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jerror.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jfdctflt.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jfdctfst.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jfdctint.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jidctflt.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jidctfst.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jidctint.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jquant1.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jquant2.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jutils.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jmemmgr.o
  CC(target) Release/obj.target/hcaptha/addon/jpeglib/jmemnobs.o
  CXX(target) Release/obj.target/hcaptha/addon/hcaptha.o
In file included from ../addon/hcaptha.cc:2:0:
../addon/cap.h:11:28: 错误：‘FunctionCallbackInfo’不是一个类型名
   static void create(const FunctionCallbackInfo<Value>& args);
                            ^
../addon/cap.h:11:28: 错误：ISO C++ 不允许声明无类型的‘parameter’ [-fpermissive]
../addon/cap.h:11:48: 错误：expected ‘,’ or ‘...’ before ‘<’ token
   static void create(const FunctionCallbackInfo<Value>& args);
                                                ^
../addon/hcaptha.cc: 在函数‘void Init(v8::Local<v8::Object>)’中:
../addon/hcaptha.cc:9:48: 错误：对‘SetMethod(v8::Local<v8::Object>&, const char [7], void (&)(int))’的调用没有匹配的函数
   NODE_SET_METHOD(target, "create", cap::create);
                                                ^
../addon/hcaptha.cc:9:48: 附注：备选是：
In file included from ../addon/hcaptha.cc:1:0:
/usr/include/node/node.h:112:6: 附注：template<class target_t> void node::SetMethod(target_t, const char*, v8::InvocationCallback)
 void SetMethod(target_t obj, const char* name,
      ^
/usr/include/node/node.h:112:6: 附注：  template argument deduction/substitution failed:
../addon/hcaptha.cc:9:48: 附注：  cannot convert ‘cap::create’ (type ‘void(int)’) to type ‘v8::InvocationCallback {aka v8::Handle<v8::Value> (*)(const v8::Arguments&)}’
   NODE_SET_METHOD(target, "create", cap::create);
                                                ^
make: *** [Release/obj.target/hcaptha/addon/hcaptha.o] 错误 1
make: 离开目录“/home/Lawrence/node_modules/ccap/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-229.20.1.el7.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/Lawrence/node_modules/ccap
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

```

**Comment by chinakids** [comment]
弄得版本必须大于0.12...(貌似nvm切换不奏效，默认都是system的gyp在起作用，只能升级system的版本,麻烦作者检查下是否指定死了...)

**Comment by DoubleSpout** [comment]
node-gyp用新版本的
