### ISSUE TITLE
求助，centos 下安装ccap@0.5.3报错，ubuntu下没问题，谢谢

### ISSUE THREAD

**Issue by wangbinlml** [DoubleSpout/ccap#59]
> ccap@0.5.3 preinstall /opt/project/service/node_modules/ccap
> node make.js

I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api and lightweight.

starting compile ccap! good luck!
/
> ccap@0.5.3 install /opt/project/service/node_modules/ccap
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 503, in gyp_main
    options.circular_check)
  File "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2692, in Load
    variables, includes, depth, check, True)
  File "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 362, in LoadTargetBuildFile
    includes, True, check)
  File "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 219, in LoadOneBuildFile
    None)
  File "binding.gyp", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 2.6.32-573.12.1.el6.x86_64
gyp ERR! command "node" "/usr/local/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/project/service/node_modules/ccap
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! ccap@0.5.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccap@0.5.3 install script.
npm ERR! This is most likely a problem with the ccap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ccap
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-573.12.1.el6.x86_64
npm ERR! command "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "install" "ccap@0.5.3"
npm ERR! cwd /opt/project/service_broker
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by DoubleSpout** [comment]
please update your node to 6.2.0, ndoe-gyp to 3.3.1,retry it~
