### ISSUE TITLE
Cannot find module '../build/Release/hcaptha.node'

### ISSUE THREAD

**Issue by eeve** [DoubleSpout/ccap#74]
os : mac osx el capitan
version: 10.11.5

node : v6.2.1
npm : 3.10.6

install  log

``` js
➜  working git:(master) ✗ npm install ccap --save
npm WARN skippingAction Module is inside a symlinked module: not running remove nan@1.7.0 node_modules/ccap/node_modules/nan
npm WARN skippingAction Module is inside a symlinked module: not running remove node-schedule@0.1.13 node_modules/ccap/node_modules/node-schedule
npm WARN skippingAction Module is inside a symlinked module: not running update async@1.4.2 node_modules/ccap/node_modules/async
npm WARN update-linked node_modules/ccap needs updating to 0.6.10 from 0.6.10 but we can't, as it's a symlink
```

run log:

``` js
module.js:442
    throw err;
    ^

Error: Cannot find module '../build/Release/hcaptha.node'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mac/working/node_modules/.npminstall/ccap/0.6.10/ccap/lib/hcap.js:4:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mac/working/node_modules/.npminstall/ccap/0.6.10/ccap/index.js:1:80)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
```

**Comment by DoubleSpout** [comment]
通过NPM安装或者下载github里的编译好的.node文件
