### ISSUE TITLE
在ubuntu 12.04上安装出错

### ISSUE THREAD

**Issue by imfine1986** [DoubleSpout/ccap#81]
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.11.0-26-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/hospital/tvbox2/node_modules/ccap
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.11.0-26-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ccap"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
```

系统版本 Ubuntu 12.04.5 LTS
Python 2.7.6
gcc (Ubuntu 4.8.1-2ubuntu1~12.04) 4.8.1
node-gyp 升级到v3.4.0 但是用的还是v3.3.1

希望大神给看下 谢谢

**Comment by DoubleSpout** [comment]
可以下载编译好的版本试试
https://github.com/DoubleSpout/ccap/tree/master/release
