### ISSUE TITLE
Python版本升级到2.7.9，报错node-gyp rebuild。用编译好的版本报错Module version mismatch.expected 47，got 46.

### ISSUE THREAD

**Issue by CherrieChen** [DoubleSpout/ccap#86]
node版本是5.5.0 ，当前Python版本是2.7.9，npm install时报node-gyp rebuild这个错。
![image](https://cloud.githubusercontent.com/assets/13508557/21520263/18cbabe6-cd2e-11e6-936e-a0aa81727542.png)

下载了作者提供的编译好的版本，启动node服务器时报错：
![image](https://cloud.githubusercontent.com/assets/13508557/21520351/c5735d94-cd2e-11e6-8595-82e372ea68a1.png)

请大神帮忙看看，谢谢！

**Comment by CherrieChen** [comment]
把node版本改成4.7.0。Python版本是2.7.9  。还是报node-gyp rebuild这个错

> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/home/jhd/node-v4.7.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:193:21)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestError (/home/jhd/node-v4.7.0-linux-x64/lib/node_modules/npm/node_modules/request/request.js:813:8)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:269:9)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at TLSSocket.emit (events.js:169:7)
gyp ERR! stack     at connectErrorNT (net.js:1013:8)
gyp ERR! System Linux 2.6.32-431.23.3.el6.x86_64
gyp ERR! command "/home/jhd/node-v4.7.0-linux-x64/bin/node" "/home/jhd/node-v4.7.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jhd/MqWebsite/node_modules/ccap
gyp ERR! node -v v4.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 2.6.32-431.23.3.el6.x86_64
npm ERR! argv "/home/jhd/node-v4.7.0-linux-x64/bin/node" "/home/jhd/node-v4.7.0-linux-x64/bin/npm" "install" "ccap"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! ccap@0.6.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccap@0.6.10 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ccap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ccap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ccap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jhd/MqWebsite/npm-debug.log
[jhd@Beta_Facade_MQ_01 MqWebsite]$ python -V
Python 2.7.9
